version: '3'

volumes:
    logs:
        driver: local

services:
    ipresence-test:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: ipresence_test
        working_dir: /var/www/html
        command:
            - /bin/sh
            - -c
            - |
                /usr/local/bin/composer.phar update
                php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8004:8080
        volumes:
            - .:/var/www/html
            - logs:/var/www/html/logs
